# Generated by Django 6.0.6 on 2026-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Filled', 'Filled'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
