# Generated by Django 6.0.6 on 2026-09-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
