# Generated by Django 6.0.6 on 2026-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='nationality',
            field=models.CharField(default='Filipino', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='returning_to_ph_to_work',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='when_willing_to_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='willing_to_work_immediately',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
