# Generated by Django 6.0.6 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='certificate_of_registration',
            field=models.FileField(blank=True, help_text='Photocopy of COR 2303', null=True, upload_to='employer_docs/cor_2303/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='dti_sec_registration',
            field=models.FileField(blank=True, help_text='Photocopy of DTI or SEC Registration', null=True, upload_to='employer_docs/dti_sec/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Photocopy of Latest Business Permit', null=True, upload_to='employer_docs/business_permits/'),
        ),
    ]
