# Generated by Django 6.0.6 on 2026-09-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='application_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed applicants before automatic closure.', null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'verification_status': 'verified'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='AdminSide.employerprofile'),
        ),
    ]
