# Generated by Django 6.0.6 on 2026-07-15 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProgramBeneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_program', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_of_program', models.CharField(choices=[('TUPAD', 'TUPAD'), ('Government_Internship_Program', 'government internship program'), ('Special_Program_For_Employment_Of_Students', 'special program for employment of students'), ('DisplacedInformalLaborProgram', 'DisplacedInformalLaborProgram')], max_length=50)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DisplacedInformalLaborProgram',
        ),
        migrations.DeleteModel(
            name='GovernmentInternshipProgram',
        ),
        migrations.DeleteModel(
            name='SpecialProgramForEmploymentOfStudents',
        ),
        migrations.DeleteModel(
            name='TupadBeneficiary',
        ),
    ]
