# Generated by Django 6.0.6 on 2026-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_jobs_application_quota_alter_jobs_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Filled', 'Filled'), ('Closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
