# Generated by Django 6.0.6 on 2026-09-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_employerprofile_certificate_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation/Position of the authorized representative (e.g., HRMO II, Administrative Officer V)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='public_doc_type',
            field=models.CharField(blank=True, choices=[('csc_appointment', 'CSC Appointment Paper / Designation Order'), ('gov_id', 'Government ID of Authorized Representative'), ('plantilla_extract', 'DBM Plantilla Extract (PSIPOP)')], help_text='Type of primary document submitted for public agency verification', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='public_verification_document',
            field=models.FileField(blank=True, help_text='Uploaded verification document for public agency', null=True, upload_to='employer_docs/public_verifications/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('lgu', 'Local Government Unit'), ('nga_regional', 'National Government Agency - Regional Office'), ('nga_national', 'National Government Agency - National Office'), ('gocc', 'Government-Owned and Controlled Corporation'), ('suc', 'State/Local University or College'), ('direct_hire', 'Direct Hire'), ('local_agency', 'Local Recruitment Agency'), ('overseas_agency', 'Overseas Recruitment Agency'), ('do_174', 'D.O. 174 Contractor/Subcontractor')], default='direct_hire', max_length=30),
        ),
    ]
