# Generated by Django 6.0.6 on 2026-09-14 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_alter_employerprofile_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='AdminSide.employerprofile'),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='AdminSide.applicantprofile'),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='applied_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_applicants', to='AdminSide.jobs'),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='is_hired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('for interview', 'For Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
