# Generated by Django 6.0.6 on 2026-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_specialprogrambeneficiaries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialprogrambeneficiaries',
            name='college_program',
        ),
        migrations.RemoveField(
            model_name='specialprogrambeneficiaries',
            name='school_name',
        ),
        migrations.AlterField(
            model_name='specialprogrambeneficiaries',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
