# Generated by Django 6.0.6 on 2026-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_jobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_id_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
