# Generated by Django 6.0.6 on 2026-09-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_applicantprofile_height_applicantprofile_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mobile_number_secondary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
