# Generated by Django 6.0.6 on 2026-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_applicantprofile_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='award_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='award_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='award_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_college_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_college_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_elem_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_elem_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_hs_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_hs_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_no_formal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_post_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='edu_tech_voc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school_status_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school_status_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='year_graduated_attended',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
