# Generated by Django 6.0.6 on 2026-09-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_alter_jobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='actively_looking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='course_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], default='unemployed', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='house_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='household_id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_4ps_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_ofw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='looking_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='unemployment_reason',
            field=models.CharField(blank=True, choices=[('fresh_grad', 'New Entrant / Fresh Graduate'), ('finished_contract', 'Finished Contract'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('laid_off_local', 'Terminated / Laid off (Local)'), ('laid_off_abroad', 'Terminated / Laid off (Abroad)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='certificate_of_registration',
            field=models.FileField(blank=True, help_text='Photocopy of COR 2303', null=True, upload_to='employer_docs/cor_2303/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation/Position of the authorized representative (e.g., HRMO II, Administrative Officer V)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='dti_sec_registration',
            field=models.FileField(blank=True, help_text='Photocopy of DTI or SEC Registration', null=True, upload_to='employer_docs/dti_sec/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='public_doc_type',
            field=models.CharField(blank=True, choices=[('csc_appointment', 'CSC Appointment Paper / Designation Order'), ('gov_id', 'Government ID of Authorized Representative'), ('plantilla_extract', 'DBM Plantilla Extract (PSIPOP)')], help_text='Type of primary document submitted for public agency verification', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='public_verification_document',
            field=models.FileField(blank=True, help_text='Uploaded verification document for public agency', null=True, upload_to='employer_docs/public_verifications/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Photocopy of Latest Business Permit', null=True, upload_to='employer_docs/business_permits/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('lgu', 'Local Government Unit'), ('nga_regional', 'National Government Agency - Regional Office'), ('nga_national', 'National Government Agency - National Office'), ('gocc', 'Government-Owned and Controlled Corporation'), ('suc', 'State/Local University or College'), ('direct_hire', 'Direct Hire'), ('local_agency', 'Local Recruitment Agency'), ('overseas_agency', 'Overseas Recruitment Agency'), ('do_174', 'D.O. 174 Contractor/Subcontractor')], default='direct_hire', max_length=30),
        ),
    ]
