# Generated by Django 6.0.6 on 2026-09-17 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_applicantprofile_actively_looking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='AdminSide.applicantprofile')),
                ('saved_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_applicants', to='AdminSide.jobs')),
            ],
            options={
                'unique_together': {('applicant', 'saved_job')},
            },
        ),
    ]
