# Generated by Django 6.0.6 on 2026-10-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0007_user_email_verification_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('dates', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='AdminSide.applicantprofile')),
            ],
        ),
    ]
