# Generated by Django 6.0.6 on 2026-10-10 10:40

import AdminSide.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0007_repair_notification_target_urls'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', AdminSide.models.AdminUserManager()),
            ],
        ),
    ]
