# Generated by Django 6.0.6 on 2026-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='actively_looking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='house_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='household_id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_4ps_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_ofw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='looking_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='unemployment_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
