# Generated by Django 6.0.6 on 2026-09-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantSide', '0002_applicantprofile_actively_looking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='preferred_job',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offeredjobs',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='applied_job',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='CareerGuidanceBeneficiary',
        ),
        migrations.DeleteModel(
            name='DisplacedInformalLaborProgram',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='employer',
        ),
        migrations.DeleteModel(
            name='GovernmentInternshipProgram',
        ),
        migrations.RemoveField(
            model_name='offeredjobs',
            name='offered_job',
        ),
        migrations.RemoveField(
            model_name='pesoactivities',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='SpecialProgramForEmploymentOfStudents',
        ),
        migrations.DeleteModel(
            name='TupadBeneficiary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ApplicantSkills',
        ),
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='OfferedJobs',
        ),
        migrations.DeleteModel(
            name='PESOActivities',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
